In [295]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [297]:
data=pd.read_csv(r"D:\capstone_project\Car_details(U).csv")
data

,vehicle_uid,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,car_record_id,car_age,price_category,km_category,owner_count,fuel_transmission,brand,price_per_km,is_diesel
0,CAR_000001,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner,1,18,Low,NaN,0.0,Petrol_Manual,Maruti,0.86,0
1,CAR_000002,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,NaN,Individual,Manual,First Owner,2,18,Low,NaN,0.0,Petrol_Manual,Maruti,2.70,0
2,CAR_000003,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner,3,13,NaN,NaN,NaN,Diesel_Manual,Hyundai,6.00,1
3,CAR_000004,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner,4,8,Low,Medium,0.0,Petrol_Manual,Datsun,5.43,0
4,CAR_000005,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner,5,11,NaN,High,0.0,Diesel_Manual,Honda,3.19,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,CAR_004336,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999.0,NaN,Diesel,Individual,Manual,Second Owner,4336,11,Mid,High,0.0,Diesel_Manual,Hyundai,5.12,1
4336,CAR_004337,Hyundai i20 Magna 1.4 CRDi,2014,409999.0,80000.0,Diesel,Individual,NaN,Second Owner,4337,11,Mid,High,0.0,Diesel_Manual,Hyundai,5.12,1
4337,CAR_004338,Maruti 800 AC BSIII,2009,110000.0,83000.0,Petrol,Individual,Manual,Second Owner,4338,16,Low,High,NaN,Petrol_Manual,Maruti,1.33,0
4338,CAR_004339,Hyundai Creta 1.6 CRDi SX Option,2016,865000.0,NaN,Diesel,Individual,Manual,First Owner,4339,9,High,High,0.0,Diesel_Manual,Hyundai,9.61,1
4339,CAR_004340,Renault KWID RXT,2016,NaN,40000.0,Petrol,Individual,Manual,First Owner,4340,9,Low,Medium,0.0,Petrol_Manual,Renault,5.62,0

# 1. Identify the maximum and minimum values of the selling_price column. 
# Calculate the average of these two values and use this average to 
# fill all missing values in selling_price.

In [299]:
data['selling_price'].isna().sum()

434

In [300]:
data['selling_price'].max()

8900000.0

In [304]:
data['selling_price'].min()

22000.0

In [305]:
avg=(8900000.0+22000.0)/2

In [306]:
data["selling_price"].isnull().sum()

434

In [308]:
data["selling_price"]=data["selling_price"].fillna(avg)

In [310]:
data["selling_price"].isnull().any()

False

# 2. Handle the km_driven and owner_count columns using an 
# appropriate real-world data-cleaning technique. 
# Justify the method used for each column based on data distribution and practical usage.

In [313]:
data["km_driven"].isnull().sum()

434

In [314]:
# for justify that which method is use mean or median thats why we describe it and check mean is greter then std or not. 
#if greater then no outlier so we use aany language, if no greater then use median
data.describe()

,year,selling_price,km_driven,car_record_id,car_age,owner_count,price_per_km,is_diesel
count,4340.000000,4.340000e+03,3906.000000,4340.000000,4340.000000,3906.0,4340.000000,4340.000000
mean,2013.090783,9.027308e+05,66231.222990,2170.500000,11.909217,0.0,88.013984,0.496083
std,4.215344,1.311959e+06,47047.819626,1252.994413,4.215344,0.0,3801.519948,0.500042
min,1992.000000,2.200000e+04,1.000000,1.000000,5.000000,0.0,0.250000,0.000000
25%,2011.000000,2.250000e+05,35000.000000,1085.750000,9.000000,0.0,2.620000,0.000000
50%,2014.000000,4.000000e+05,60000.000000,2170.500000,11.000000,0.0,6.000000,0.000000
75%,2016.000000,7.500000e+05,90000.000000,3255.250000,14.000000,0.0,15.555000,1.000000
max,2020.000000,8.900000e+06,806599.000000,4340.000000,33.000000,0.0,250000.000000,1.000000

In [319]:
data["km_driven"].median()

60000.0

In [321]:
data["km_driven"]=data["km_driven"].fillna(60000.0)

In [323]:
data["owner_count"]=data["owner_count"].fillna(0.0)

In [325]:
data.isnull().any()

vehicle_uid          False
name                 False
year                 False
selling_price        False
km_driven            False
fuel                  True
seller_type          False
transmission          True
owner                False
car_record_id        False
car_age              False
price_category        True
km_category           True
owner_count          False
fuel_transmission    False
brand                False
price_per_km         False
is_diesel            False
dtype: bool

# 3. For the km_category column, 50% of the missing values should be 
# filled with the most frequently occurring category. 
# The remaining 50% of missing values should be filled with the value "High".

In [327]:
data["km_category"].isnull().any()

True

In [328]:
data["km_category"].isnull().sum()

434

In [330]:
434/2

217.0

In [332]:
mode=data["km_category"].mode()
mode

0    Medium
Name: km_category, dtype: object

In [333]:
data["km_category"]=data["km_category"].fillna(mode[0],limit=217)

In [334]:
data["km_category"]=data["km_category"].fillna("High",limit=217)

# 4. Fill missing values in the price_category column using the most 
# frequently occurring category in the dataset. 
# If it is not possible to determine whether the category is generated 
# manually or automatically, replace missing values with "Unknown".

In [337]:
data["price_category"].mode()

0    Low
Name: price_category, dtype: object

In [343]:
data["price_category"]=data["price_category"].fillna("Low")

In [345]:
data["price_category"].isnull().any()

False

In [347]:
data["transmission"].mode()

0    Manual
Name: transmission, dtype: object

In [348]:
data["transmission"]=data["transmission"].fillna("Manual")

In [350]:
data["transmission"].isnull().any()

False

# 5. For the fuel column, distribute all missing values equally among 
# the existing unique fuel types. 
# Each unique fuel value must be assigned the same number of missing records.

In [352]:
data["fuel"].isnull().sum()

435

In [354]:
data["fuel"].unique()

array(['Petrol', nan, 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [356]:
435/5

87.0

In [357]:
data["fuel"]=data["fuel"].fillna("Petrol",limit=87)
data["fuel"]=data["fuel"].fillna("Diesel",limit=87)
data["fuel"]=data["fuel"].fillna("CNG",limit=87)
data["fuel"]=data["fuel"].fillna("LPG",limit=87)
data["fuel"]=data["fuel"].fillna("Electric",limit=87)

In [358]:
data["fuel"].isnull().any()

False

In [360]:
data.to_csv("capstone_python.csv",index=False)

In [361]:
pwd

'D:\\capstone_project\\sql'

# 6. After completing all the data cleaning steps, split the final cleaned 
# dataset into two CSV files and export them.  
#First file => 
#Name it: vehicle_info 
#This file should contain only the following columns: 
#vehicle_uid, name, year, fuel, seller_type, transmission, owner, 
#brand, car_age, etc. 
#Second file=> 
#Name it: vehicle_sales 
#This file should contain only the following columns:  
#vehicle_uid, selling_price, km_driven, price_category, km_category, etc.

In [369]:
vehicle_info = data[['vehicle_uid','name','year','fuel','seller_type',
                   'transmission','owner','brand','car_age']]

In [371]:
vehicle_sales = data[['vehicle_uid','selling_price','km_driven',
                    'price_category','km_category']]

In [373]:
vehicle_info.to_csv("vehicle_info.csv",index=False)

In [374]:
vehicle_sales.to_csv("vehicle_sales.csv",index=False)

In [377]:
pwd

'D:\\capstone_project\\sql'

In [378]:
cd D:\capstone_project\sql

D:\capstone_project\sql